kind: pipeline
type: kubernetes
name: default

steps:
- name: deps
  image: golang
  volumes:
  - name: cache
    path: /go
  commands:
    - "mkdir -p $GOPATH/bin $GOPATH/src/github.com/N0Cloud/dinject"
    - "cp -R /drone/src $GOPATH/src/github.com/N0Cloud/dinject"
    - "curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh"
    - "cd $GOPATH/src/github.com/N0Cloud/dinject && dep ensure -v"
- name: build
  image: golang
  volumes:
  - name: cache
    path: /go
  depends_on:
  - deps
  commands:
  - go build
- name: test
  image: golang
  volumes:
  - name: cache
    path: /go
  depends_on:
  - deps
  commands:
  - "go test -v --race"

volumes:
- name: cache
  temp: {}
