workspace:
  base: /go
  path: src/github.com/N0Cloud/dinject
pipeline:
  build:
    image: golang:${GO_VERSION}
    commands:
      - go version
      - go get github.com/stretchr/testify/assert
      - go get ./...
      - go test -v --race
      - go build
matrix:
  GO_VERSION:
    - latest
    - "1.8"
    - "1.7"