workspace:
  base: /go
  path: src/github.com/N0Cloud/dinject
pipeline:
  dep:
    image: golang:${GO_VERSION}
    commands:
      - "mkdir -p $GOPATH/bin && echo $GOPATH"
      - "curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh"
      - "dep ensure -v"
  build:
    image: golang:${GO_VERSION}
    commands:
      - "go build"
  test:
    image: golang:${GO_VERSION}
    commands:
      - "go test -v --race"
matrix:
  GO_VERSION:
    - latest
    - "1.10"
    - "1.9"
    - "1.8"
    - "1.7"