kind: pipeline
type: kubernetes
name: default

steps:
- name: deps
  image: golang
  volumes:
  - name: cache
    path: /go
  commands:
    - "mkdir -p $GOPATH/bin"
    - "curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh"
    - "dep ensure -v"
- name: build
  image: golang
  volumes:
  - name: cache
    path: /go
  commands:
  - go build
- name: test
  image: golang
  volumes:
  - name: cache
    path: /go
  commands:
  - "go test -v --race"

volumes:
- name: cache
  temp: {}
